# Generated by Django 5.2.3 on 2025-07-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=90, verbose_name='correo')),
                ('password', models.CharField(max_length=10, verbose_name='password')),
            ],
        ),
    ]
